
# Develop a guessing game that performs the following: 
# - The system will automatically generate a random number between 1 and 100.
# - Users can insert any number between 1 and 100
# - The program will  be able to compare the number generated by the system and the number that has been entered by the user. The program shall print out one of the following options to help the user improve their next guess:
# You are right, great job!
# Your guess is low, try again!
# Your guess is high, try again!
# The program exits when the user guess matches the number generated by the system
import random
num = random.randint(num(1,100))
# the code above generates random numbers between 1 and 100
# the next code will be assigning a variable for the guess,
user_guess = int(input("Welcome to the guessing game! Please guess a number between 1 and 100: "))
#the above line will display an input box for the user to enter their guess
while user_guess != num:
#while loop to keep the game running until the user guesses the correct number
    if user_guess < num:
        print("Your guess is low, try again!")
        user_guess = int(input("Enter your next guess: "))
    else:
        print("Your guess is high, try again!")
        user_guess = int(input("Enter your next guess: "))


